### ISSUE TITLE
Supplied Checkpoints Weight Mismatch

### ISSUE THREAD

**Issue by helenlai** [thejonaslab/vonmises-icml-2023#2]
<img width="947" alt="image" src="https://github.com/thejonaslab/vonmises-icml-2023/assets/40118589/5cfa49e2-1afb-495b-a10e-43674175b14a">

Hi there,

I have tried to run the VonMisesNet inference with pretrained checkpoint using the example smiles but ran into a shape mismatch err. It seems like the script is creating 129 features which is as detailed in the paper, whereas the supplied checkpoint only have 124 features. Could you please check on this, and supply the correct checkpoints if needed?
It is a rather issue, I hope this could be addressed as soon as possible. 

Many thanks,
Helen

**Comment by ks8** [comment]
Hi Helen,

Thanks for reaching out, and I'm sorry that you're experiencing this issue. As a test, I just tried re-installing the conda environment and running inference using the example, and I didn't get any errors. Just to double check, have you made any changes to the conda environment or to the source code?

Kirk

**Comment by helenlai** [comment]
Hi Kirk, 

Thank you for your response. The only modification I made is to the .yml file to disenable tiny graph as the installation has repeatedly failed. I have reinstalled the environment on my end too but still have the same error. Can I check how many features does the model have on your end? And if saved model weight you used is the same as the one in the master branch?

Many thanks,
Helen

**Comment by ks8** [comment]
Hi Helen, 

Interestingly enough, I'm seeing that after the featurization, there are only 124 total features. You are correct that in the paper, in Table 4, we said there would be 129 features. It's possible that this is a typo, but I wonder why my featurization yields 124 and yours yields 129. I'm going through the individual features one by one, and it looks like I'm only seeing 4 chiral type tags here https://github.com/thejonaslab/vonmises-icml-2023/blob/main/vonmises/featurize_mols.py#L245, whereas in Table 4, we claimed where would be 9 possible chiral types. This difference of 5 could account for the 129 vs 124 features.

Can you do me a favor and print the value of `num_atom_features` here https://github.com/thejonaslab/vonmises-icml-2023/blob/main/vonmises/graph_builders.py#L140, and can you also print the value of `self.chi_types` here https://github.com/thejonaslab/vonmises-icml-2023/blob/main/vonmises/featurize_mols.py#L245, and let me know what you see? I'm hopeful that we can find the root cause.

**Comment by ks8** [comment]
Hi Helen,

Can you also check what version of RDKit is installed in your conda environment? The RDKit version specified in our environment.yml file is 2022.03.5. With that version, `len(list(rdchem.ChiralType.values.values())) = 4`. When I installed the latest RDKit in a separate environment, which is version 2023.03.2, I see `len(list(rdchem.ChiralType.values.values())) = 9`. I wonder if you've somehow installed the more recent RDKit version, and therefore are getting 9 chiral types instead of 4? This could also explain our paper Table -- we might have checked the set of chiral types available in the most recent RDKit version, even though that's not the version specified our conda environment.

**Comment by helenlai** [comment]
Right! That seems to be the reason, I have downgraded RDKit to 2022.03.5 and the weight shape matches now. Thank you for your help Kirk :)

**Comment by ks8** [comment]
Sure thing, glad to help! Out of curiosity, when you created the conda environment, did it originally have the correct RDKit environment and then you upgraded it? Or did it automatically have the newest RDKit? I want to make sure that there isn’t an issue with the environment.yml that would cause other ppl to have the same problem.

**Comment by helenlai** [comment]
Sure, I did not upgrade the RDKit, the one installed by the environment.yml file was the latest one.

**Comment by ks8** [comment]
Interesting, ok I’ll try to fix that and/or leave a note in in the instructions. Thanks!
